### PR TITLE
Add dotd test

### PR DESCRIPTION
**Pull request by felixmulder**
I'm just guessing the syntax of ruby at this point. How do I test this locally?

### CODE REVIEW

**Comment by liufengyun** [comment]
You can run `brew install dotty.rb` to install locally, then run `brew test dotty`.

**Comment by felixmulder** [comment]
I'm not sure travis is actually testing the new formula, but rather the old one?

**Comment by felixmulder** [comment]
Ah, but then it should do that on the CI too right?

**Comment by liufengyun** [comment]
Yes, travis is testing the old formula, we need to update `osx` script to `brew install dotty.rb`.

**Comment by felixmulder** [comment]
I'll do it an publish a new release

**Pull request merged**
