### PR TITLE
Update to Dotty 0.6.0-RC1

### PR DESCRIPTION
**Pull request by allanrenucci**

### CODE REVIEW

**Comment by allanrenucci** [comment]
@liufengyun Can you check `brew` does not complain about the `sha256` and merge if it is OK?

**Comment by liufengyun** [comment]
I confirm it works perfectly on OSX.

**Comment by liufengyun** [comment]
I verified again, it works perfectly on my Mac. The failure on Travis is spurious.

**Comment by liufengyun** [comment]
It's a problem with `dotd` (Dottydoc), `dotc` and `dotr` are not affected.

**Pull request merged**
