### PR TITLE
Patch Dotty 0.5.0-RC1 archive

### PR DESCRIPTION
**Pull request by allanrenucci**

### CODE REVIEW

**Comment by liufengyun** [comment]
@allanrenucci Seems the digest is incorrect.

**Comment by liufengyun** [comment]
@allanrenucci I'm merging this, as otherwise people will have problems install dotty using brew.

**Comment by allanrenucci** [comment]
I'm curious. How did you generate this value?

**Comment by liufengyun** [comment]
@allanrenucci It can be generated as follows:

```bash
wget https://github.com/lampepfl/dotty/releases/download/0.5.0-RC1/dotty-0.5.0-RC1.tar.gz -O dotty-0.6.tar.gz
sha256sum dotty-0.6.tar.gz
```

**Pull request merged**
